apiVersion: v1

name: observability

description: Description

type: application

version: 0.1.0

appVersion: "1.0.0"

maintainers:
- name: José Fabián Vargas Cascante
  email: fabian.vargas.cascante@gmail.com
