global:
  scrape_interval: "15s"
  scrape_timeout: "15s"
  evaluation_interval: "15s"

scrape_configs:

- job_name: 'flask-app'
  static_configs:
  - targets: ['app-sv:5000']
    labels:
      app: flask-app
  metrics_path: /metrics
